name: Update GitHub Profile Stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate selected trophies
        uses: soulteary/github-profile-trophy-action@v1.0.0
        with:
        options: 'username=Hsadikot95S&theme=onedark&title=Experience,Commits,Followers&column=3&margin-w=25&margin-h=15&no-bg=true&no-frame=true'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit generated stats
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add profile/trophy.svg

          git commit -m "Update GitHub profile stats" || exit 0

          git push
